version: '3.9'
services:
  dev-db:
    image: postgres:latest
    container_name: db_postgres_nestjs-tutorial
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  test-db:
    image: postgres:latest
    container_name: db_test_postgres_nestjs-tutorial
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
